/*******************************************
** pulled from pgAdmin 
** might be easier to use the RPostgreSQL dbWriteTable 
** function to create this table - once table is created, 
** the r-to-pg load pattern is truncate/reload
********************************************/

CREATE TABLE pbp.plays_2023
(
    play_id double precision,
    game_id text COLLATE pg_catalog."default",
    old_game_id text COLLATE pg_catalog."default",
    home_team text COLLATE pg_catalog."default",
    away_team text COLLATE pg_catalog."default",
    season_type text COLLATE pg_catalog."default",
    week integer,
    posteam text COLLATE pg_catalog."default",
    posteam_type text COLLATE pg_catalog."default",
    defteam text COLLATE pg_catalog."default",
    side_of_field text COLLATE pg_catalog."default",
    yardline_100 double precision,
    game_date text COLLATE pg_catalog."default",
    quarter_seconds_remaining double precision,
    half_seconds_remaining double precision,
    game_seconds_remaining double precision,
    game_half text COLLATE pg_catalog."default",
    quarter_end double precision,
    drive double precision,
    sp double precision,
    qtr double precision,
    down double precision,
    goal_to_go double precision,
    "time" text COLLATE pg_catalog."default",
    yrdln text COLLATE pg_catalog."default",
    ydstogo double precision,
    ydsnet double precision,
    "desc" text COLLATE pg_catalog."default",
    play_type text COLLATE pg_catalog."default",
    yards_gained double precision,
    shotgun double precision,
    no_huddle double precision,
    qb_dropback double precision,
    qb_kneel double precision,
    qb_spike double precision,
    qb_scramble double precision,
    pass_length text COLLATE pg_catalog."default",
    pass_location text COLLATE pg_catalog."default",
    air_yards double precision,
    yards_after_catch double precision,
    run_location text COLLATE pg_catalog."default",
    run_gap text COLLATE pg_catalog."default",
    field_goal_result text COLLATE pg_catalog."default",
    kick_distance double precision,
    extra_point_result text COLLATE pg_catalog."default",
    two_point_conv_result text COLLATE pg_catalog."default",
    home_timeouts_remaining double precision,
    away_timeouts_remaining double precision,
    timeout double precision,
    timeout_team text COLLATE pg_catalog."default",
    td_team text COLLATE pg_catalog."default",
    td_player_name text COLLATE pg_catalog."default",
    td_player_id text COLLATE pg_catalog."default",
    posteam_timeouts_remaining double precision,
    defteam_timeouts_remaining double precision,
    total_home_score double precision,
    total_away_score double precision,
    posteam_score double precision,
    defteam_score double precision,
    score_differential double precision,
    posteam_score_post double precision,
    defteam_score_post double precision,
    score_differential_post double precision,
    no_score_prob double precision,
    opp_fg_prob double precision,
    opp_safety_prob double precision,
    opp_td_prob double precision,
    fg_prob double precision,
    safety_prob double precision,
    td_prob double precision,
    extra_point_prob double precision,
    two_point_conversion_prob double precision,
    ep double precision,
    epa double precision,
    total_home_epa double precision,
    total_away_epa double precision,
    total_home_rush_epa double precision,
    total_away_rush_epa double precision,
    total_home_pass_epa double precision,
    total_away_pass_epa double precision,
    air_epa double precision,
    yac_epa double precision,
    comp_air_epa double precision,
    comp_yac_epa double precision,
    total_home_comp_air_epa double precision,
    total_away_comp_air_epa double precision,
    total_home_comp_yac_epa double precision,
    total_away_comp_yac_epa double precision,
    total_home_raw_air_epa double precision,
    total_away_raw_air_epa double precision,
    total_home_raw_yac_epa double precision,
    total_away_raw_yac_epa double precision,
    wp double precision,
    def_wp double precision,
    home_wp double precision,
    away_wp double precision,
    wpa double precision,
    vegas_wpa double precision,
    vegas_home_wpa double precision,
    home_wp_post double precision,
    away_wp_post double precision,
    vegas_wp double precision,
    vegas_home_wp double precision,
    total_home_rush_wpa double precision,
    total_away_rush_wpa double precision,
    total_home_pass_wpa double precision,
    total_away_pass_wpa double precision,
    air_wpa double precision,
    yac_wpa double precision,
    comp_air_wpa double precision,
    comp_yac_wpa double precision,
    total_home_comp_air_wpa double precision,
    total_away_comp_air_wpa double precision,
    total_home_comp_yac_wpa double precision,
    total_away_comp_yac_wpa double precision,
    total_home_raw_air_wpa double precision,
    total_away_raw_air_wpa double precision,
    total_home_raw_yac_wpa double precision,
    total_away_raw_yac_wpa double precision,
    punt_blocked double precision,
    first_down_rush double precision,
    first_down_pass double precision,
    first_down_penalty double precision,
    third_down_converted double precision,
    third_down_failed double precision,
    fourth_down_converted double precision,
    fourth_down_failed double precision,
    incomplete_pass double precision,
    touchback double precision,
    interception double precision,
    punt_inside_twenty double precision,
    punt_in_endzone double precision,
    punt_out_of_bounds double precision,
    punt_downed double precision,
    punt_fair_catch double precision,
    kickoff_inside_twenty double precision,
    kickoff_in_endzone double precision,
    kickoff_out_of_bounds double precision,
    kickoff_downed double precision,
    kickoff_fair_catch double precision,
    fumble_forced double precision,
    fumble_not_forced double precision,
    fumble_out_of_bounds double precision,
    solo_tackle double precision,
    safety double precision,
    penalty double precision,
    tackled_for_loss double precision,
    fumble_lost double precision,
    own_kickoff_recovery double precision,
    own_kickoff_recovery_td double precision,
    qb_hit double precision,
    rush_attempt double precision,
    pass_attempt double precision,
    sack double precision,
    touchdown double precision,
    pass_touchdown double precision,
    rush_touchdown double precision,
    return_touchdown double precision,
    extra_point_attempt double precision,
    two_point_attempt double precision,
    field_goal_attempt double precision,
    kickoff_attempt double precision,
    punt_attempt double precision,
    fumble double precision,
    complete_pass double precision,
    assist_tackle double precision,
    lateral_reception double precision,
    lateral_rush double precision,
    lateral_return double precision,
    lateral_recovery double precision,
    passer_player_id text COLLATE pg_catalog."default",
    passer_player_name text COLLATE pg_catalog."default",
    passing_yards double precision,
    receiver_player_id text COLLATE pg_catalog."default",
    receiver_player_name text COLLATE pg_catalog."default",
    receiving_yards double precision,
    rusher_player_id text COLLATE pg_catalog."default",
    rusher_player_name text COLLATE pg_catalog."default",
    rushing_yards double precision,
    lateral_receiver_player_id text COLLATE pg_catalog."default",
    lateral_receiver_player_name text COLLATE pg_catalog."default",
    lateral_receiving_yards double precision,
    lateral_rusher_player_id text COLLATE pg_catalog."default",
    lateral_rusher_player_name text COLLATE pg_catalog."default",
    lateral_rushing_yards double precision,
    lateral_sack_player_id text COLLATE pg_catalog."default",
    lateral_sack_player_name text COLLATE pg_catalog."default",
    interception_player_id text COLLATE pg_catalog."default",
    interception_player_name text COLLATE pg_catalog."default",
    lateral_interception_player_id text COLLATE pg_catalog."default",
    lateral_interception_player_name text COLLATE pg_catalog."default",
    punt_returner_player_id text COLLATE pg_catalog."default",
    punt_returner_player_name text COLLATE pg_catalog."default",
    lateral_punt_returner_player_id text COLLATE pg_catalog."default",
    lateral_punt_returner_player_name text COLLATE pg_catalog."default",
    kickoff_returner_player_name text COLLATE pg_catalog."default",
    kickoff_returner_player_id text COLLATE pg_catalog."default",
    lateral_kickoff_returner_player_id text COLLATE pg_catalog."default",
    lateral_kickoff_returner_player_name text COLLATE pg_catalog."default",
    punter_player_id text COLLATE pg_catalog."default",
    punter_player_name text COLLATE pg_catalog."default",
    kicker_player_name text COLLATE pg_catalog."default",
    kicker_player_id text COLLATE pg_catalog."default",
    own_kickoff_recovery_player_id text COLLATE pg_catalog."default",
    own_kickoff_recovery_player_name text COLLATE pg_catalog."default",
    blocked_player_id text COLLATE pg_catalog."default",
    blocked_player_name text COLLATE pg_catalog."default",
    tackle_for_loss_1_player_id text COLLATE pg_catalog."default",
    tackle_for_loss_1_player_name text COLLATE pg_catalog."default",
    tackle_for_loss_2_player_id text COLLATE pg_catalog."default",
    tackle_for_loss_2_player_name text COLLATE pg_catalog."default",
    qb_hit_1_player_id text COLLATE pg_catalog."default",
    qb_hit_1_player_name text COLLATE pg_catalog."default",
    qb_hit_2_player_id text COLLATE pg_catalog."default",
    qb_hit_2_player_name text COLLATE pg_catalog."default",
    forced_fumble_player_1_team text COLLATE pg_catalog."default",
    forced_fumble_player_1_player_id text COLLATE pg_catalog."default",
    forced_fumble_player_1_player_name text COLLATE pg_catalog."default",
    forced_fumble_player_2_team text COLLATE pg_catalog."default",
    forced_fumble_player_2_player_id text COLLATE pg_catalog."default",
    forced_fumble_player_2_player_name text COLLATE pg_catalog."default",
    solo_tackle_1_team text COLLATE pg_catalog."default",
    solo_tackle_2_team text COLLATE pg_catalog."default",
    solo_tackle_1_player_id text COLLATE pg_catalog."default",
    solo_tackle_2_player_id text COLLATE pg_catalog."default",
    solo_tackle_1_player_name text COLLATE pg_catalog."default",
    solo_tackle_2_player_name text COLLATE pg_catalog."default",
    assist_tackle_1_player_id text COLLATE pg_catalog."default",
    assist_tackle_1_player_name text COLLATE pg_catalog."default",
    assist_tackle_1_team text COLLATE pg_catalog."default",
    assist_tackle_2_player_id text COLLATE pg_catalog."default",
    assist_tackle_2_player_name text COLLATE pg_catalog."default",
    assist_tackle_2_team text COLLATE pg_catalog."default",
    assist_tackle_3_player_id text COLLATE pg_catalog."default",
    assist_tackle_3_player_name text COLLATE pg_catalog."default",
    assist_tackle_3_team text COLLATE pg_catalog."default",
    assist_tackle_4_player_id text COLLATE pg_catalog."default",
    assist_tackle_4_player_name text COLLATE pg_catalog."default",
    assist_tackle_4_team text COLLATE pg_catalog."default",
    tackle_with_assist double precision,
    tackle_with_assist_1_player_id text COLLATE pg_catalog."default",
    tackle_with_assist_1_player_name text COLLATE pg_catalog."default",
    tackle_with_assist_1_team text COLLATE pg_catalog."default",
    tackle_with_assist_2_player_id text COLLATE pg_catalog."default",
    tackle_with_assist_2_player_name text COLLATE pg_catalog."default",
    tackle_with_assist_2_team text COLLATE pg_catalog."default",
    pass_defense_1_player_id text COLLATE pg_catalog."default",
    pass_defense_1_player_name text COLLATE pg_catalog."default",
    pass_defense_2_player_id text COLLATE pg_catalog."default",
    pass_defense_2_player_name text COLLATE pg_catalog."default",
    fumbled_1_team text COLLATE pg_catalog."default",
    fumbled_1_player_id text COLLATE pg_catalog."default",
    fumbled_1_player_name text COLLATE pg_catalog."default",
    fumbled_2_player_id text COLLATE pg_catalog."default",
    fumbled_2_player_name text COLLATE pg_catalog."default",
    fumbled_2_team text COLLATE pg_catalog."default",
    fumble_recovery_1_team text COLLATE pg_catalog."default",
    fumble_recovery_1_yards double precision,
    fumble_recovery_1_player_id text COLLATE pg_catalog."default",
    fumble_recovery_1_player_name text COLLATE pg_catalog."default",
    fumble_recovery_2_team text COLLATE pg_catalog."default",
    fumble_recovery_2_yards double precision,
    fumble_recovery_2_player_id text COLLATE pg_catalog."default",
    fumble_recovery_2_player_name text COLLATE pg_catalog."default",
    sack_player_id text COLLATE pg_catalog."default",
    sack_player_name text COLLATE pg_catalog."default",
    half_sack_1_player_id text COLLATE pg_catalog."default",
    half_sack_1_player_name text COLLATE pg_catalog."default",
    half_sack_2_player_id text COLLATE pg_catalog."default",
    half_sack_2_player_name text COLLATE pg_catalog."default",
    return_team text COLLATE pg_catalog."default",
    return_yards double precision,
    penalty_team text COLLATE pg_catalog."default",
    penalty_player_id text COLLATE pg_catalog."default",
    penalty_player_name text COLLATE pg_catalog."default",
    penalty_yards double precision,
    replay_or_challenge double precision,
    replay_or_challenge_result text COLLATE pg_catalog."default",
    penalty_type text COLLATE pg_catalog."default",
    defensive_two_point_attempt double precision,
    defensive_two_point_conv double precision,
    defensive_extra_point_attempt double precision,
    defensive_extra_point_conv double precision,
    safety_player_name text COLLATE pg_catalog."default",
    safety_player_id text COLLATE pg_catalog."default",
    season integer,
    cp double precision,
    cpoe double precision,
    series double precision,
    series_success double precision,
    series_result text COLLATE pg_catalog."default",
    order_sequence double precision,
    start_time text COLLATE pg_catalog."default",
    time_of_day text COLLATE pg_catalog."default",
    stadium text COLLATE pg_catalog."default",
    weather text COLLATE pg_catalog."default",
    nfl_api_id text COLLATE pg_catalog."default",
    play_clock text COLLATE pg_catalog."default",
    play_deleted double precision,
    play_type_nfl text COLLATE pg_catalog."default",
    special_teams_play double precision,
    st_play_type text COLLATE pg_catalog."default",
    end_clock_time text COLLATE pg_catalog."default",
    end_yard_line text COLLATE pg_catalog."default",
    fixed_drive double precision,
    fixed_drive_result text COLLATE pg_catalog."default",
    drive_real_start_time text COLLATE pg_catalog."default",
    drive_play_count double precision,
    drive_time_of_possession text COLLATE pg_catalog."default",
    drive_first_downs double precision,
    drive_inside20 double precision,
    drive_ended_with_score double precision,
    drive_quarter_start double precision,
    drive_quarter_end double precision,
    drive_yards_penalized double precision,
    drive_start_transition text COLLATE pg_catalog."default",
    drive_end_transition text COLLATE pg_catalog."default",
    drive_game_clock_start text COLLATE pg_catalog."default",
    drive_game_clock_end text COLLATE pg_catalog."default",
    drive_start_yard_line text COLLATE pg_catalog."default",
    drive_end_yard_line text COLLATE pg_catalog."default",
    drive_play_id_started double precision,
    drive_play_id_ended double precision,
    away_score integer,
    home_score integer,
    location text COLLATE pg_catalog."default",
    result integer,
    total integer,
    spread_line double precision,
    total_line double precision,
    div_game integer,
    roof text COLLATE pg_catalog."default",
    surface text COLLATE pg_catalog."default",
    temp integer,
    wind integer,
    home_coach text COLLATE pg_catalog."default",
    away_coach text COLLATE pg_catalog."default",
    stadium_id text COLLATE pg_catalog."default",
    game_stadium text COLLATE pg_catalog."default",
    aborted_play double precision,
    success double precision,
    passer text COLLATE pg_catalog."default",
    passer_jersey_number integer,
    rusher text COLLATE pg_catalog."default",
    rusher_jersey_number integer,
    receiver text COLLATE pg_catalog."default",
    receiver_jersey_number integer,
    pass double precision,
    rush double precision,
    first_down double precision,
    special double precision,
    play double precision,
    passer_id text COLLATE pg_catalog."default",
    rusher_id text COLLATE pg_catalog."default",
    receiver_id text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    jersey_number integer,
    id text COLLATE pg_catalog."default",
    fantasy_player_name text COLLATE pg_catalog."default",
    fantasy_player_id text COLLATE pg_catalog."default",
    fantasy text COLLATE pg_catalog."default",
    fantasy_id text COLLATE pg_catalog."default",
    out_of_bounds double precision,
    home_opening_kickoff double precision,
    qb_epa double precision,
    xyac_epa double precision,
    xyac_mean_yardage double precision,
    xyac_median_yardage integer,
    xyac_success double precision,
    xyac_fd double precision,
    xpass double precision,
    pass_oe double precision
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE pbp.plays_2023
    OWNER to pbp_worker;